     <main class="home">
          
          <section class="introduction">
               
               <article class="introText">
                    
                    <h1>3WA Tasks</h1>
                    
                    <h2>The best way to optimize your time</h2>
                    
                    <p>Based on the Einsenhower method, our application five you the best order to do what you have to do.</p>
                    
               </article>
               
               <article class=connextionPages>
                    
                    <a href="register.php">Register</a>
                    <a href="login.php">Login</a>
                    
               </article>               
               
               
          </section>
          
          
          <section class="introImage">
               
               <img src="./assets/images/home_image.png" alt="to do list image"></img>
               
          </section>
          
          
     </main>