<!doctype html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <title>To do list</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
     <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
     <header>
          
          <a href="account.php">3WA Tasks</a>
          
     </header>
     
     <?php include $template ?>
     
     <footer>
          
          <p>©2024 - 3W Academy</p>
          
     </footer>
     
</body>
</html>