<main class="register">
    
    <section class="registerText">
        
        <h1>Register</h1>
        
        <p>Welcome in the world of perfect task priorization !</p>
        
    </section>
    
    <section class="registerForm">
        
        <form method="post" action="signup.php">
            
            <label for="name">Username
            <input type="text" name="name" required/>
            </label>
            
            <label for="email">Email
            <input type="text" name="email" required/>
            </label>
            
            <label for="password">Password
            <input type="text" name="password" required/>
            </label>
            
            <input type="submit" value="register" class="submit"/>
        </form>
        
    </section>
    
    
</main>