<main class="register">
    
    <section class="registerText">
        
        <h1>Register</h1>
        
        <p>Welcome in the world of perfect task priorization !</p>
        
    </section>
    
    <section class="registerForm">
        
        <form method="POST" action="register.php">
            
            <label for="name">Username
            <input type="text" name="username" />
            </label>
            
            <label for="email">Email
            <input type="email" name="email" />
            </label>
            
            <label for="password">Password
            <input type="text" name="password" />
            </label>
            
            <input type="submit" value="Register" class="submit"/>
        </form>
        
    </section>
    
    
    <section class="onceSubmit">
        
        <?php if(isset($errors) && !empty($errors)) : ?>
            <?php foreach ($errors as $error) : ?>
                <p class="displayError"><?= $error ?></p>
            <?php endforeach; ?>
        <?php elseif(isset($errors)) : ?>
            <p class="noError">You register</p>
            <a href="login.php">Login</a>
        <?php endif; ?>
        
        
    </section>
    
    
</main>